algo = input('Digite qualquer coisa, um número, uma palavra...')
print('Agora vamos analisar')
print('O tipo primitivo destes caracteres é', type(algo))
print('Só tem espaços?',algo.isspace())
print('Só tem números',algo.isnumeric())
print('Apenas contém letras?',algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('São letras maiúsculas?', algo.isupper())
print('São letras minúsculas?', algo.islower())
print('Estão capitalizadas?', algo.istitle())