nome = str(input('Digite seu nome completo:'))
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é {}'.format(nome.upper()))
print('Seu nome em letras minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
nome1 = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(nome1[0],len(nome1[0])))
