numero = int(input('Informe um número:'))
num = str(numero)
print('Analisando o número {}'.format(numero))
print('Unidade: {}'.format(num[3]))
print('Dezena: {}'.format(num[2]))
print('Centena: {}'.format(num[1]))
print('Milhar: {}'.format(num[0]))
