print('****DESAFIO 001****')
nome = input('Qual é o seu nome?')
print('Olá',nome,', prazer em te conhecer!')
print('...........................')
print('****DESAFIO 002****')
Dia = input('Dia =')
Mês = input('Mês =')
Ano = input('Ano =')
print('Você nasceu no dia',Dia,'de',Mês,'de',Ano,'. Correto?')
print('...........................')
print('****DESAFIO 003****')
n1 = input('Digite um número')
n2 = input('Agora digite outro')
n3 = n1+n2
print('A junção destes números resulta em',n3)
