print('Exemplo 1')
n1 = int(input('digite um número'))
n2 = int(input('agora outro'))
s = n1+n2
print('a soma destes números vale {}.'.format(s))
print('************************************')
print('Exemplo 2')
n1 = input('Digite um valor:')
print(type(n1))
print('*************************************')
print('Exemplo 3')
n1 = int(input('Digite um número:'))
print(type(n1))
print('*************************************')
print('Exemplo 4')
n1 = int(input('Digite um valor:'))
n2 = int(input('Digite outro valor:'))
s = n1 + n2
# print('A soma entre', n1,'e',n2,'vale',s)
print('A soma entre {} e {} vale {}'.format(n1,n2,s))
print('**************************************')
print('Exemplo 5')
n = bool(input('Digite algo:'))
print(n)
print('*****************************************')
n = input('Digite algo:')
print(n.isnumeric())
print('******************************************')
n = input('Digite algo:')
print(n.isalpha())
print('********************************************')
n = input('Digite algo:')
print(n.isalnum())
# Existe vários outros tipos de 'is'. explore e aprenda!
print('**************Desafio 003****************')
n1 = int(input('Digite um número:'))
n2 = int(input('Digite outro:'))
n3 = n1 + n2
print('A soma entre {} e {} vale {}'.format(n1,n2,n3))
print('**************Desafio 004*****************')
n = input('Digite qualquer coisa:')
print('Numérico:',n.isnumeric())
print('Alfabético:',n.isalpha())
print('Alfanumérico:',n.isalnum())
print('Está em caixa alta:',n.isupper())
print('Está em letras minúsculas:',n.islower())
